# Generated by Django 4.2.11 on 2024-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
