# Generated by Django 4.2.11 on 2024-03-21 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomplete',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordercomplete',
            name='executor_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='ordercomplete',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order'),
        ),
    ]
