# Generated by Django 4.2.11 on 2024-03-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_description_alter_order_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/orders/'),
        ),
        migrations.AddField(
            model_name='ordercomplete',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/avatars/'),
        ),
    ]
