# Generated by Django 4.2.11 on 2024-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_img_ordercomplete_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercomplete',
            name='time_complete',
        ),
        migrations.AlterField(
            model_name='ordercomplete',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
