# Generated by Django 4.2.11 on 2024-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_coordinates_alter_ordercomplete_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
