# Generated by Django 4.2.11 on 2024-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_coordinates_order_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomplete',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
