FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev

RUN pip install --upgrade pip

# Install Python dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt


# Make port 8000 available to the world outside this container
EXPOSE 8000

COPY start.sh start.sh
RUN  chmod +x start.sh
#CMD ["gunicorn", "--bind", "0.0.0.0:8000", "core.wsgi:application"]
#CMD ["manage.py runserver"]
CMD  ./start.sh